stages:
  get_data:
    cmd: python src/get_data.py data/boston.csv
    deps:
    - src/get_data.py
    outs:
    - data/boston.csv
  engineering:
    cmd: python src/feature_engineering.py data/boston.csv params.yaml data/boston_features.csv
    deps:
    - data/boston.csv
    params:
    - engineering.log
    - engineering.log_features
    outs:
    - data/boston_features.csv
